# Generated by Django 6.0.5 on 2026-05-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=20, unique=True)),
                ('vessel_type', models.CharField(max_length=100)),
                ('capacity_tons', models.FloatField()),
                ('fuel_capacity_tons', models.FloatField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('distance_nm', models.FloatField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='operations.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_knots', models.FloatField()),
                ('fuel_consumption_tons_per_day', models.FloatField()),
                ('engine_temperature_celsius', models.FloatField()),
                ('weather_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_records', to='operations.voyage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('delay_risk', 'Delay Risk'), ('fuel_anomaly', 'Fuel Anomaly'), ('engine_overheat', 'Engine Overheat'), ('weather_warning', 'Weather Warning'), ('route_deviation', 'Route Deviation'), ('speed_anomaly', 'Speed Anomaly')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Info'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=3)),
                ('message', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telemetry_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='operations.telemetryrecord')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='operations.voyage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
