# Generated by Django 6.0.5 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
