# Generated by Django 6.0.5 on 2026-06-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_vessel_detected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='detected_at',
        ),
    ]
