# Generated by Django 6.0.5 on 2026-06-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_vessel_detected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalalert',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
